name: ${name}
main: com.vypnito.arena.arena
version: ${version}
api-version: '1.21'
author: Vypnito
description: A dynamic region management system with a GUI editor.
commands:
  arena:
    description: "Main command for the arena system."
    usage: "/arena <subcommand>"
    aliases: [ar]
    permission: 1v1rooms.admin
permissions:
  1v1rooms.admin:
    description: "Allows user to manage arenas."
    default: op